tap "homebrew/bundle"
tap "jesseduffield/lazygit"
# Next generation open source RPC library and framework
brew "grpc"
# Generate compilation database for clang tooling
brew "bear"
# GNU compiler collection
brew "gcc"
# Insanely fast image printing in your terminal
brew "catimg"
# Statistics utility to count lines of code
brew "cloc"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNOME XML library
brew "libxml2"
# GitHub command-line tool
brew "gh"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Asynchronous event library
brew "libevent"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Interactive cheatsheet tool for the command-line
brew "navi"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Command-line interface for SQLite
brew "sqlite"
# Platform built on V8 to build network applications
brew "node"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Python dependency management tool
brew "pipenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
